<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload08df9e5707583cd114f64d8c187f5dcd($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'clansofcaledonia\\bread' => '/Bread.php',
            'clansofcaledonia\\cheese' => '/Cheese.php',
            'clansofcaledonia\\exception' => '/Exception.php',
            'clansofcaledonia\\good' => '/Good.php',
            'clansofcaledonia\\grain' => '/Grain.php',
            'clansofcaledonia\\market' => '/Market.php',
            'clansofcaledonia\\milk' => '/Milk.php',
            'clansofcaledonia\\offer' => '/Offer.php',
            'clansofcaledonia\\outofrangeexception' => '/OutOfRangeException.php',
            'clansofcaledonia\\pound' => '/Pound.php',
            'clansofcaledonia\\pricelist' => '/PriceList.php',
            'clansofcaledonia\\pricelistbuilder' => '/PriceListBuilder.php',
            'clansofcaledonia\\unit' => '/Unit.php',
            'clansofcaledonia\\whisky' => '/Whisky.php',
            'clansofcaledonia\\wool' => '/Wool.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload08df9e5707583cd114f64d8c187f5dcd', true);
// @codeCoverageIgnoreEnd
